### PR TITLE
no host key checking

### PR DESCRIPTION
**Pull request by andrewschoen**
Fixes: https://github.com/ceph/ceph-installer/issues/52

### CODE REVIEW

**Comment by ktdreyer** [comment]
We might as well drop the entire `/setup/host_key` endpoint, right ?

**Comment by ktdreyer** [comment]
ie revert the whole of https://github.com/ceph/ceph-installer/pull/54

**Comment by andrewschoen** [comment]
@ktdreyer I believe I have all your input incorporated now. Thanks!

**Comment by ktdreyer** [comment]
Looks good to me!

**Pull request merged**
