### PR TITLE
setup.py: use print() function

### PR DESCRIPTION
**Pull request by ktdreyer**
For Python 3

### CODE REVIEW

**Comment by ktdreyer** [comment]
@andrewschoen you love setup.py

**Comment by alfredodeza** [comment]
Why do we need Python 3 support in setup.py?

**Comment by ktdreyer** [comment]
There's no immediate reason. I was just using that same code on another project where it runs `setup.py` through py3, and it failed to run, so I figured we might as well patch it here too

**Comment by alfredodeza** [comment]
packaging with Python 3 might fail on other places too. This doesn't hurt though. Will merge

**Pull request merged**
