### PR TITLE
lock the ansible version to 1.9.4

### PR DESCRIPTION
**Pull request by andrewschoen**
I was seeing this issue in 2.0.0.2:

https://github.com/ansible/ansible/issues/13876

I do not see that in 1.9.4 though, so we'll pin the ansible version to
that for now.

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
LGTM

**Comment by ktdreyer** [comment]
actually, want to modify setup.py as well? We might as well add Ansible to `install_requires`.

**Comment by ktdreyer** [comment]
we could probably remove this `pip install` command entirely, if it's in `setup.py`

**Comment by andrewschoen** [comment]
@ktdreyer ceph-installer won't look inside a virtualenv for ansible though and these deployment scripts put everything in a virtualenv. That's why I'm using the ``pip install`` here.

**Comment by ktdreyer** [comment]
I see, ok!

**Pull request merged**
